package org.homio.addon.imou.internal.cloud.dto;

import java.util.List;
import lombok.Getter;
import lombok.Setter;
import lombok.ToString;

@Getter
@Setter
@ToString
// https://open.imoulife.com/book/en/http/device/live/getLiveStreamInfo.html
public class ImouDeviceLiveStreamsDTO {

    private List<Stream> streams;

    @Getter
    @Setter
    @ToString
    public static class Stream {

        // token for live broadcast
        private String liveToken;
        // Live stream hls access address
        private String hls;
        // Stream type (0: HD main stream; 1: SD secondary stream) (when the live broadcast address is generated by the rtsp source, this field is not
        // available)
        private int streamId;
        // Status
        private String status;
    }
}
